### ISSUE TITLE
Tarefas para os bixos

### ISSUE THREAD

**Issue by tiagoshibata** [ThundeRatz/Bixos-2016#1]
Façam um esforço e postem coisas no fórum, se o processo for mal planejado e ruim, entram bixos ruins também.

Atualmente, estamos com (o que penso pelo menos, comentem aí):
- Cada veterano cria um repositório privado para seus bixos, deixamos aqui o que for das tarefas para todos verem. Quando acabar o PS a gente passa tudo para cá.
- Aulas be-a-bá para eles assistirem. [Esse post](http://forum.thunderatz.org/viewtopic.php?f=207&t=2170#p38797) mostra o básico: Shell e navegação e manuais, basicamente, e algum tutorial interativo de Git.
- Aulas: Precisamos discutir quais. Talvez tenhamos que ajudá-los a instalar Linux também.
- Leitura de um char device genérico. Pensei em escrever um driver pra dispositivo bem simples (que retornasse uma string qualquer quando lido) e pedir para eles compilarem e lerem ele primeiro. As vantagens são tem um dispositivo mais simples para eles testarem antes do Bluetooth e aprenderem a usar make e compilar um driver.
- Configuração do receptor bluetooth em modo serial (bem be boa essa parte). Fazer um script que chame os programas certos.
- Programa para receber leituras pela serial (discutam qual linguagem passamos, C ou C++?) com as características citadas no fórum (integridade). Pedir um Makefile ou configuração com autotools do projeto.

O parte de envio de dados pela serial do uC fica com comp ou elétrica? Acho que é importante para ambos aprenderem.

@Dupletor @d-nery @Mitsuo-Tiramisu e quem mais interessar.

**Comment by d-nery** [comment]
Respondi no fórum :)

**Comment by tiagoshibata** [comment]
Vou abrir uma issue para cada assunto e a gente coloca algum responsável e revisa o que foi escrito. A ideia é acabar antes do fim do carnaval.
