### ISSUE TITLE
Aula C

### ISSUE THREAD

**Issue by tiagoshibata** [ThundeRatz/Bixos-2016#4]
Aula básica de C ou links para aulas boas. Vale fazer uns slides para apresentar também.

**Comment by d-nery** [comment]
Vou tentar fazer haha, alguma sugestão de até que parte de C a gente passa?

**Comment by tiagoshibata** [comment]
O que for precisar, estruturas e ponteiros vão ser meio necessários em algum momento, acho que precisa chegar no básico dos dois.

**Comment by d-nery** [comment]
Nessa também já falaremos de C pra AVR?
E eu já posso admitir que já vai ter tido a aula de Linux e Linha de Comando?

**Comment by tiagoshibata** [comment]
Acho que AVR vai ser separado, linux e linha de comando vêm antes.
